# routes/book_routes.py

from flask import request, jsonify
from routes import book_bp
from db import query_all, query_one, execute

@book_bp.get("")
def list_books():
    """
    Trả về danh sách books kèm theo Price riêng cho từng Format.
    """
    category_name = request.args.get("category")
    sort = request.args.get("sort")

    # Sửa query: Thêm 'Price', E.Price vào JSON Object
    base_sql = """
        SELECT 
            B.BookID,
            B.Title,
            B.Description,
            MIN(E.Price) AS MinPrice,
            GROUP_CONCAT(DISTINCT C.Name ORDER BY C.Name SEPARATOR ', ') AS Categories,
            JSON_ARRAYAGG(
                JSON_OBJECT(
                    'FormatID', F.FormatID, 
                    'FormatType', F.FormatType,
                    'Price', E.Price
                )
            ) AS Formats
        FROM Book B
        LEFT JOIN Edition E ON B.BookID = E.BookID
        LEFT JOIN Format F ON E.EditionID = F.EditionID
        LEFT JOIN BookCategory BC ON B.BookID = BC.BookID
        LEFT JOIN Category C ON BC.CategoryID = C.CategoryID
    """

    params = []
    conditions = []

    if category_name:
        conditions.append("C.Name = %s")
        params.append(category_name)

    if conditions:
        base_sql += " WHERE " + " AND ".join(conditions)

    base_sql += " GROUP BY B.BookID, B.Title, B.Description "

    if sort == "price_asc":
        base_sql += " ORDER BY MinPrice ASC "
    elif sort == "price_desc":
        base_sql += " ORDER BY MinPrice DESC "
    elif sort == "title_desc":
        base_sql += " ORDER BY B.Title DESC "
    else:
        base_sql += " ORDER BY B.Title ASC "

    rows = query_all(base_sql, params)
    return jsonify(rows)


@book_bp.get("/<book_id>")
def get_book_detail(book_id):
    sql = """
        SELECT 
            B.BookID,
            B.Title,
            B.Description,
            MIN(E.Price) AS MinPrice,
            GROUP_CONCAT(DISTINCT C.Name ORDER BY C.Name SEPARATOR ', ') AS Categories
        FROM Book B
        LEFT JOIN Edition E ON B.BookID = E.BookID
        LEFT JOIN BookCategory BC ON B.BookID = BC.BookID
        LEFT JOIN Category C ON BC.CategoryID = C.CategoryID
        WHERE B.BookID = %s
        GROUP BY B.BookID, B.Title, B.Description
    """
    row = query_one(sql, [book_id])
    if not row:
        return jsonify({"error": "Book not found"}), 404
    return jsonify(row)


@book_bp.post("")
def create_book():
    """
    Tạo sách mới
    """
    data = request.get_json() or {}
    title = data.get("title")
    description = data.get("description")

    if not title:
        return jsonify({"error": "title is required"}), 400

    sql = "INSERT INTO Book (Title, Description) VALUES (%s, %s)"
    execute(sql, [title, description])
    return jsonify({"message": "Book created (BookID generated by trigger)"}), 201


@book_bp.put("/<book_id>")
def update_book(book_id):
    data = request.get_json() or {}
    title = data.get("title")
    description = data.get("description")

    exist = query_one("SELECT BookID FROM Book WHERE BookID = %s", [book_id])
    if not exist:
        return jsonify({"error": "Book not found"}), 404

    sql = "UPDATE Book SET Title = %s, Description = %s WHERE BookID = %s"
    execute(sql, [title, description, book_id])
    return jsonify({"message": "Book updated"})


@book_bp.delete("/<book_id>")
def delete_book(book_id):
    exist = query_one("SELECT BookID FROM Book WHERE BookID = %s", [book_id])
    if not exist:
        return jsonify({"error": "Book not found"}), 404

    sql = "DELETE FROM Book WHERE BookID = %s"
    execute(sql, [book_id])
    return jsonify({"message": "Book deleted"})